baseURL = 'https://example.org/'
languageCode = 'ru-ru'
title = ' '
theme = "blowfish"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  defaultAppearance = "light"
  autoSwitchAppearance = true

[assets]
  [[assets.css]]
    href = "css/index.css"

ignoreLogs = ['warning-goldmark-raw-html']